import subprocess
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
OUT = ROOT / "evaluation_summary_final"
LATEX = OUT / "latex"
PREP = ROOT / "data" / "cnn_dataset" / "prepared_v1"
MODELS = ROOT / "models_trained"

OUT.mkdir(parents=True, exist_ok=True)
LATEX.mkdir(parents=True, exist_ok=True)

warnings = []


def banner(text):
    print("\n" + "=" * 62)
    print(f" {text}")
    print("=" * 62)


def run_script(name):
    path = SCRIPTS / name
    if not path.exists():
        warnings.append(f"{name} not found - skipped")
        return False
    banner(name)
    r = subprocess.run([sys.executable, str(path)])
    if r.returncode != 0:
        warnings.append(f"{name} exited with code {r.returncode} - "
                        f"see its message above")
        return False
    return True


def to_latex(df, stem, caption, label):
    """Write a standalone tabular block that can be \\input into the thesis."""
    if df is None or df.empty:
        return
    body = df.to_latex(index=False, escape=True, na_rep="-",
                       column_format="l" + "r" * (df.shape[1] - 1))
    text = (
        "% auto-generated by scripts/make_dissertation_outputs.py\n"
        "\\begin{table}[htbp]\n\\centering\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{tab:{label}}}\n"
        f"{body}"
        "\\end{table}\n"
    )
    (LATEX / f"{stem}.tex").write_text(text, encoding="utf-8")


def safe_read(path):
    if not path.exists():
        warnings.append(f"missing: {path.relative_to(ROOT)}")
        return None
    try:
        return pd.read_csv(path)
    except Exception as exc:
        warnings.append(f"could not read {path.name}: {exc}")
        return None


# ------------------------------------------------------------------ 1-3
run_script("diagnose_runs.py")
run_script("analyze_results.py")
run_script("analyze_robustness.py")
run_script("analyze_transient.py")


# -------------------------------------------------------------------- 4
banner("training curves")
hist = safe_read(MODELS / "training_history.csv")
if hist is not None and not hist.empty:
    hist.insert(0, "epoch", range(1, len(hist) + 1))

    fig, ax = plt.subplots(1, 2, figsize=(11, 4.4))
    ax[0].plot(hist["epoch"], hist["loss"], label="train")
    if "val_loss" in hist:
        ax[0].plot(hist["epoch"], hist["val_loss"], label="validation")
    ax[0].set_xlabel("Epoch")
    ax[0].set_ylabel("Huber loss")
    ax[0].set_title("CNN training loss")
    ax[0].set_yscale("log")

    ax[1].plot(hist["epoch"], hist["mae"], label="train")
    if "val_mae" in hist:
        ax[1].plot(hist["epoch"], hist["val_mae"], label="validation")
    ax[1].set_xlabel("Epoch")
    ax[1].set_ylabel("Mean absolute error")
    ax[1].set_title("CNN training MAE")

    for a in ax:
        a.grid(alpha=0.3)
        a.legend()
    plt.tight_layout()
    plt.savefig(OUT / "cnn_training_curves.png", dpi=160)
    plt.close()

    best = hist.loc[hist["val_mae"].idxmin()] if "val_mae" in hist else None
    summary = pd.DataFrame([{
        "Epochs run": len(hist),
        "Best epoch": int(best["epoch"]) if best is not None else "-",
        "Best val MAE": round(float(best["val_mae"]), 5)
        if best is not None else "-",
        "Best val loss": round(float(best["val_loss"]), 6)
        if best is not None and "val_loss" in hist else "-",
        "Final train MAE": round(float(hist["mae"].iloc[-1]), 5),
        "Final LR": f"{hist['learning_rate'].iloc[-1]:.2e}"
        if "learning_rate" in hist else "-",
    }])
    summary.to_csv(OUT / "cnn_training_summary.csv", index=False)
    to_latex(summary, "cnn_training_summary",
             "Convolutional network training summary.", "cnn_training")
    print(summary.to_string(index=False))
    print(f"Saved -> {OUT / 'cnn_training_curves.png'}")


# -------------------------------------------------------------------- 5
banner("dataset composition")
cats = safe_read(PREP / "prepared_category_counts.csv")
dsum = safe_read(PREP / "prepared_dataset_summary.csv")

if cats is not None and not cats.empty:
    cats = cats.copy()
    total = cats["samples"].sum()
    cats["percentage"] = (cats["samples"] / total * 100).round(2)
    cats.loc[len(cats)] = ["TOTAL", total, 100.00]
    cats.to_csv(OUT / "dataset_composition.csv", index=False)
    to_latex(cats, "dataset_composition",
             "Composition of the balanced training set.", "dataset")
    print(cats.to_string(index=False))

    plt.figure(figsize=(7, 4.2))
    plot_df = cats[cats["category"] != "TOTAL"]
    plt.bar(plot_df["category"], plot_df["samples"], color="#3377bb")
    plt.ylabel("Samples")
    plt.title("Balanced dataset composition")
    plt.xticks(rotation=20, ha="right")
    plt.grid(axis="y", alpha=0.3)
    plt.gca().set_axisbelow(True)
    plt.tight_layout()
    plt.savefig(OUT / "dataset_composition.png", dpi=160)
    plt.close()

if dsum is not None and not dsum.empty:
    r = dsum.iloc[0]
    tidy = pd.DataFrame([
        {"Property": "Raw collected samples", "Value": int(r["raw_samples"])},
        {"Property": "Selected source samples",
         "Value": int(r["selected_source_samples"])},
        {"Property": "Prepared samples (after mirroring)",
         "Value": int(r["prepared_samples"])},
        {"Property": "Target range",
         "Value": f"{r['target_minimum']:.2f} to {r['target_maximum']:.2f}"},
        {"Property": "Target mean", "Value": f"{r['target_mean']:.4f}"},
        {"Property": "Target standard deviation",
         "Value": f"{r['target_standard_deviation']:.4f}"},
        {"Property": "Centre / medium / strong (%)",
         "Value": f"{r['centre_percentage']:.1f} / "
                  f"{r['medium_percentage']:.1f} / "
                  f"{r['strong_percentage']:.1f}"},
    ])
    tidy.to_csv(OUT / "dataset_summary_table.csv", index=False)
    to_latex(tidy, "dataset_summary",
             "Prepared dataset statistics.", "dataset_stats")
    print()
    print(tidy.to_string(index=False))


# -------------------------------------------------------------------- 6
banner("LaTeX tables from the analysis outputs")
for csv_name, stem, caption, label in [
    ("method_comparison.csv", "method_comparison",
     "Baseline track: P, PD and CNN+PD hybrid compared "
     "(mean $\\pm$ standard deviation over repeat runs).", "method_comp"),
    ("all_runs.csv", "all_runs",
     "Per-run results on the baseline track.", "all_runs"),
    ("robustness_completion.csv", "robustness_completion",
     "Track completion against line-to-floor contrast.", "robustness"),
    ("transient_response.csv", "transient_response",
     "Offset recovery with the curve-following component removed.",
     "transient"),
]:
    df = OUT / csv_name
    if df.exists():
        d = pd.read_csv(df)
        to_latex(d, stem, caption, label)
        print(f"  latex/{stem}.tex")
    else:
        warnings.append(f"{csv_name} not produced - "
                        f"the matching analysis step did not complete")


# -------------------------------------------------------------------- 7
banner("index")
index = ["# Dissertation results index",
         "",
         "Every file below is in `evaluation_summary_final/`.",
         "",
         "## Chapter: Methodology",
         "",
         "| Artefact | File | Use |",
         "|---|---|---|",
         "| Dataset composition table | `dataset_composition.csv` | "
         "how the balanced training set is split |",
         "| Dataset statistics table | `dataset_summary_table.csv` | "
         "sample counts and label distribution |",
         "| Dataset composition figure | `dataset_composition.png` | "
         "bar chart of the same |",
         "",
         "## Chapter: CNN training",
         "",
         "| Artefact | File | Use |",
         "|---|---|---|",
         "| Training curves | `cnn_training_curves.png` | "
         "loss and MAE, train vs validation |",
         "| Training summary | `cnn_training_summary.csv` | "
         "best epoch and best validation MAE |",
         "",
         "## Chapter: Results - baseline comparison",
         "",
         "| Artefact | File | Use |",
         "|---|---|---|",
         "| Headline table | `method_comparison.csv` | "
         "the main P vs PD vs Hybrid table, mean +/- SD |",
         "| Per-run table | `all_runs.csv` | "
         "appendix evidence that the means are not single runs |",
         "| Accuracy figure | `method_comparison.png` | "
         "MAE and smoothness bar charts |",
         "| Error trace | `error_over_time.png` | "
         "cross-track error against time |",
         "",
         "## Chapter: Results - robustness",
         "",
         "| Artefact | File | Use |",
         "|---|---|---|",
         "| Completion vs contrast | `robustness_completion.csv` | "
         "the table that justifies the CNN |",
         "| Robustness figure | `robustness_sweep.png` | "
         "completion and detector visibility against contrast |",
         "| Per-run robustness | `robustness_runs.csv` | appendix |",
         "",
         "## Chapter: Results - transient response",
         "",
         "| Artefact | File | Use |",
         "|---|---|---|",
         "| Transient table | `transient_response.csv` | "
         "overshoot, rise time, settling time |",
         "| Transient figure | `transient_response.png` | "
         "offset recovery curves |",
         "",
         "## LaTeX",
         "",
         "`latex/*.tex` holds a ready-to-`\\input` tabular block for each "
         "table above.",
         ""]

if warnings:
    index += ["## Warnings from this build", ""]
    index += [f"- {w}" for w in warnings]
    index += [""]

(OUT / "DISSERTATION_RESULTS.md").write_text("\n".join(index),
                                             encoding="utf-8")

print(f"  {OUT / 'DISSERTATION_RESULTS.md'}")

if warnings:
    print("\nWarnings:")
    for w in warnings:
        print(f"  - {w}")

print("\nDone.")
